# Generated by Django 3.1.1 on 2020-09-25 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='enteryear',
            field=models.DateField(default=datetime.datetime(2020, 9, 25, 15, 46, 26, 725661), verbose_name='入学年份'),
        ),
    ]
