# Generated by Django 3.1.1 on 2020-09-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpa', '0002_auto_20200925_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='enteryear',
            field=models.IntegerField(blank=True, default=2017, max_length=5, null=True, verbose_name='入学年份'),
        ),
    ]
