# Generated by Django 3.1.1 on 2020-09-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpa', '0004_auto_20200925_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='selfassessment',
            field=models.IntegerField(blank=True, choices=[(5, '完全掌握'), (4, '熟练'), (3, '良好'), (1, '一般'), (-5, '几乎为零')], max_length=100, null=True, verbose_name='知识掌握程度'),
        ),
    ]
