# Generated by Django 3.1.1 on 2020-09-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpa', '0005_auto_20200928_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='frommajor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='本科专业'),
        ),
        migrations.AddField(
            model_name='ques',
            name='fromschool',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='本科大学'),
        ),
    ]
