# Generated by Django 3.1.1 on 2020-09-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpa', '0006_auto_20200930_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='ques',
            name='otherhardship',
            field=models.TextField(blank=True, null=True, verbose_name='其他问题'),
        ),
        migrations.AddField(
            model_name='ques',
            name='hardship',
            field=models.ManyToManyField(blank=True, null=True, to='sgpa.Hardship', verbose_name='存在的问题'),
        ),
    ]
