# Generated by Django 3.1.1 on 2020-09-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(blank=True, choices=[('level1', 'level1'), ('level21', 'level21'), ('model selection', 'model selection'), ('machine learning', 'machine learning'), ('theoretic statistics', 'theoretic statistics'), ('bayesian inference', 'bayesian inference'), ('bio statistics', 'bio statistics'), ('mm', 'mm'), ('level23', 'level23'), ('level3', 'level3')], max_length=100, null=True, verbose_name='关键词分类')),
            ],
        ),
    ]
